name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Release binary
  # You may pin to the exact commit or the version.
  # uses: Guerra24/upload-to-release@933304c241627d9260fc449fa504becb04f365a3
      uses: Guerra24/upload-to-release@v1.0.0
      with:
    # Artifact name
        name: lssaid
    # Path to the file to upload
        path: target/release/lssaid
    # Content type for the file
        content-type: application/octet-stream
    # secrets.GITHUB_TOKEN
        repo-token: ${{ secrets.GITHUB_TOKEN }}
