name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'target/release/lssaid'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
